name: Run Tests

on:
  workflow_dispatch:
    inputs:
      test_run_id:
        description: 'Test run identifier'
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, dom, fileinfo, mysql, xml
        coverage: xdebug
    
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    
    - name: Install Dependencies
      run: composer install --no-ansi --no-interaction --no-progress
      
    - name: Generate key
      run: php artisan key:generate
      
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
      
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
        
    - name: Run Tests with Coverage
      run: |
        XDEBUG_MODE=coverage ./vendor/bin/phpunit --coverage-clover=coverage.xml --log-junit=test-report.xml
        
    - name: Generate Test Results JSON
      id: generate-results
      run: |
        # Extract coverage percentage
        COVERAGE=$(grep -o 'lines:\s*[0-9.]*%' coverage.xml | grep -o '[0-9.]*')
        
        # Extract test counts
        TOTAL_TESTS=$(grep -o 'tests="[0-9]*"' test-report.xml | head -1 | grep -o '[0-9]*')
        FAILURES=$(grep -o 'failures="[0-9]*"' test-report.xml | head -1 | grep -o '[0-9]*')
        ERRORS=$(grep -o 'errors="[0-9]*"' test-report.xml | head -1 | grep -o '[0-9]*')
        SKIPPED=$(grep -o 'skipped="[0-9]*"' test-report.xml | head -1 | grep -o '[0-9]*')
        
        # Calculate passed tests
        PASSED=$((TOTAL_TESTS - FAILURES - ERRORS - SKIPPED))
        
        # Create results JSON
        cat > results.json << EOF
        {
          "status": "completed",
          "completed_at": "$(date -u +"%Y-%m-%dT%H:%M:%SZ")",
          "results": {
            "coverage_percentage": $COVERAGE,
            "total_tests": $TOTAL_TESTS,
            "passed_tests": $PASSED,
            "failed_tests": $((FAILURES + ERRORS)),
            "skipped_tests": $SKIPPED
          }
        }
        EOF
        
        cat results.json
        
    - name: Call Webhook
      run: |
        curl -X POST \
          -H "Content-Type: application/json" \
          -d @results.json \
          https://githubworkflow.requestcatcher.com/?test_run_id=${{ github.event.inputs.test_run_id }}
